# -*- coding: utf-8 -*-
"""AI Gen

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mWqXRaQUpGosn1tqQSnQOaypOLVhrUjp
"""

# Commented out IPython magic to ensure Python compatibility.
!pip install pygit2==1.12.2
# %cd /content
!git clone https://github.com/lllyasviel/Fooocus.git
# %cd /content/Fooocus
!python entry_with_update.py --share